name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  google_sign_in: 5.0.4
  firebase_auth: 1.4.1
  firebase_core: 1.3.0
  cloud_firestore: 2.2.2
  flutter_feather_icons: 2.0.0+1
  font_awesome_flutter: 9.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

